version: 1.2
workflows:
- name: DownloadBams
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/DownloadBams.wdl
  testParameterFiles:
- name: MergeAndSubsample
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/MergeAndSubsample.wdl
  testParameterFiles:
